branch-defaults:
  master:
    environment: lostsalesapp
    group_suffix: null
environment-defaults:
  lostsalesapp:
    branch: master
    repository: lostsalesapp
global:
  application_name: lostsalesapp
  branch: null
  default_ec2_keyname: ose-test
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
