branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: lostsalesApp
  branch: master
  default_ec2_keyname: aaron
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
