# Generated by Django 3.1 on 2020-08-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.FloatField()),
                ('alu', models.FloatField()),
                ('subsidiary', models.CharField(choices=[(100, 'HealthPlus'), (200, 'CasaBella')], max_length=20)),
                ('Description', models.CharField(max_length=200)),
                ('attributes', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Productss',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('Manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subsidiary', models.CharField(choices=[(100, 'HealthPlus'), (200, 'CasaBella')], max_length=20)),
                ('store_code', models.CharField(max_length=5)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region')),
            ],
            options={
                'verbose_name': 'stores',
                'verbose_name_plural': 'storess',
            },
        ),
    ]
