# Generated by Django 3.1 on 2020-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200820_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='alu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
