# Generated by Django 3.1 on 2020-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200820_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='alu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='upc',
            field=models.IntegerField(),
        ),
    ]
