# Generated by Django 3.1 on 2020-08-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_lostsales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostsales',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
