# Generated by Django 3.1 on 2020-08-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200827_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostsales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.products'),
        ),
    ]
