# Generated by Django 3.1 on 2020-09-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200827_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostsales',
            options={'verbose_name': 'Lostsales', 'verbose_name_plural': 'Lostsales'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name': 'stores', 'verbose_name_plural': 'stores'},
        ),
        migrations.AddField(
            model_name='lostsales',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stores'),
        ),
    ]
