# Generated by Django 3.1 on 2020-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200909_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='subsidiary',
            field=models.CharField(choices=[('100', 'HealthPlus'), ('200', 'CasaBella')], max_length=20),
        ),
    ]
